FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:0.2.5

# Configure pkg-config for cross compilation
ENV PKG_CONFIG_ALLOW_CROSS=1

RUN dpkg --add-architecture arm64 && \
  apt-get update && \
  apt-get install -y --no-install-recommends  libasound2-dev:arm64 && \
  rm -rf /var/lib/apt/lists/*
