FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu@sha256:24476a75e3d3175d98f30008fa91f39ec0c657082dd74aee2874b621e53885b0

RUN dpkg --add-architecture arm64

# pull x86_64 tools from the main archive, and ARM64 packages from the ports archive
RUN sed -i -e 's/^deb \([^\[]\)/deb [arch=amd64] \1/g' /etc/apt/sources.list && \
  sed -e 's/^deb \[arch=amd64\]/deb [arch=arm64]/g' \
  -e 's|http://archive.ubuntu.com/ubuntu/|http://ports.ubuntu.com/ubuntu-ports/|g' \
  -e 's|http://security.ubuntu.com/ubuntu/|http://ports.ubuntu.com/ubuntu-ports/|g' \
  /etc/apt/sources.list > /etc/apt/sources.list.d/arm64.list

RUN apt-get update && apt-get install -y --no-install-recommends \
  pkg-config \
  libasound2-dev:arm64 \
  libjack-jackd2-dev:arm64 \
  libssl-dev:arm64 && \
  rm -rf /var/lib/apt/lists/*

# Rust's pkg-config needs to know exactly where to find the cross-compiled libraries
ENV PKG_CONFIG_PATH="/usr/lib/aarch64-linux-gnu/pkgconfig"
ENV PKG_CONFIG_ALLOW_CROSS=1
