[shutdown]
# what state to leave the lights in
# "blackout": set all lights to 0
# "default": reasonable neutral low-level
# "restore": return to the state we started with where applicable
mode = "Restore"

[shutdown.defaults]
1 = 128 # set channel 1 to 50% on exit

[midi]
# Leave device_name blank to force selection at startup
device_name = ""

[midi.mappings]
"36" = "kick"
"38" = "snare"
"42" = "hihat"
"44" = "crash"

[[behavior]]
id = "kick"
decay_seconds = 0.5
velocity_curve = "hard"
decay_profile = "exponential"

[[behavior]]
id = "snare"
decay_seconds = 0.2
velocity_curve = "soft"
decay_profile = "linear"

[[behavior]]
id = "hihat"
decay_seconds = 0.2
velocity_curve = "soft"
decay_profile = "linear"

[[behavior]]
id = "crash"
decay_seconds = 2.0
velocity_curve = "hard"
decay_profile = "linear"

[output]
[output.artnet]
target_ip = "255.255.255.255:6454"
universe = 0

[[output.dmx]]
id = "kick"
channel = 0
color = [255, 0, 0]

[[output.dmx]]
id = "snare"
channel = 3
color = [255, 255, 0]

[[output.dmx]]
id = "hihat"
channel = 7

[[output.dmx]]
id = "crash"
channel = 10
