[shutdown]
# what state to leave the lights in
# "blackout": set all lights to 0
# "default": reasonable neutral low-level
# "restore": return to the state we started with where applicable
mode = "Restore"

[shutdown.defaults]
1 = 128 # set channel 1 to 50% on exit

[midi]
# Partial match for now
device_name = "Impact GXP49"

[artnet]
target_ip = "255.255.255.255:6454"
universe = 0

[[mapping]]
note = 36           # Kick
dmx_channel = 0
decay_seconds = 0.5

[[mapping]]
note = 38           # Snare
dmx_channel = 4
decay_seconds = 0.2
