name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8ad5bc06d33534 # v2.1.0
        with:
          generate_release_notes: true

  build-release:
    name: Build & Upload Release Binary
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            use_cross: true
          - target: aarch64-apple-darwin
            os: macos-latest
            use_cross: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Linux system dependencies
        if: runner.os == 'Linux' && !matrix.use_cross
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libasound2-dev libjack-jackd2-dev

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@a54c339952cd4ad0aa73838f9befc41020465a3a # stable
        with:
          targets: ${{ matrix.target }}

      - name: Upload Binary
        uses: taiki-e/upload-rust-binary-action@e876007e0573e0b82f80165a250325206233513a # v1.23.0
        with:
          bin: pulseplex
          target: ${{ matrix.target }}
          cross: ${{ matrix.use_cross }}
          token: ${{ secrets.GITHUB_TOKEN }}
